### ISSUE TITLE
Icon stuck in top-left corner of my desktop!

### ISSUE THREAD

**Issue by JFiscella** [d-torrance/wmforecast#4]
The icon is stuck in the top-left corner of my desktop, and it won't allow my icons to be arranged to the left side of my desktop because of this! It also is always-on-top of all windows, which is not expected behavior.

This is probably due to my usage of Lubuntu desktop.

A suggestion is to allow moving of the icon through a configuration file or in the options GUI.

http://imgur.com/a/8opar

**Comment by d-torrance** [comment]
Thanks for your report!

wmforecast is working as intended in Lubuntu/LXDE/Openbox *if* you intend to use it as a dockapp.  It's placed in the dock, which by default goes in the top left of the screen, exactly as you reported.

See http://openbox.org/wiki/Help:Configuration#Dock for configuration options.

Would you prefer to use wmforecast as a normal window with window decorations that you could drag around?  I could definitely add a "windowed" option in a future version.
