### ISSUE TITLE
wmforecast shows as "untitled" in tint2

### ISSUE THREAD

**Issue by onstrt** [d-torrance/wmforecast#5]
Reading
     //code.google.com/archive/p/tint2/issues?page=5  (2) 
and 
    //github.com/ValveSoftware/steam-for-linux/issues/25 **Steam title (tint2) #25**
this seems to mirror the "steam-for-linux/" issue.

**Comment by d-torrance** [comment]
Thanks for your report!  It's now fixed in git.
