### ISSUE TITLE
Not show current temp.

### ISSUE THREAD

**Issue by BourzRoss** [d-torrance/wmforecast#9]
It work now! Thank! 
But in dockapp itself and in baloon "Current Conditions: Unknow 0°"

**Comment by d-torrance** [comment]
Yeah, I've had the same issue the last couple days.  It appears to be a bug in libgweather, because Gnome Weather is also showing "Unknown".

Maybe the Norwegian Meteorological Institute has changed their API or something?

**Comment by BourzRoss** [comment]
Oh! Noooo! Only not changed API!))))

**Comment by d-torrance** [comment]
The good news is that now it's the Gnome developers that would have to deal with any API changes.  wmforecast should work as long as libgweather works.

Actually, in the last few minutes, both wmforecast and Gnome Weather started working again for me!  I'm not sure what was going on.

**Comment by BourzRoss** [comment]
Yeah! Mistycal!...For me work too from this moment. I 'm close this issue
